# This line of code will allow shorter imports
from currency_conversion.forex_data import ForexData
from currency_conversion.keltner_channel import KeltnerForexData
from currency_conversion.trailing_stops import TrailingStopsData
from currency_conversion.trailing_stops2_testing_data import TrailingStopsTrainingData2
from currency_conversion.trailing_stops2 import TrailingStopsData2
from currency_conversion.trailing_stops2_real_time_data import TrailingStopsData2RealTimeData
from currency_conversion.trailing_stops3_testing_data import TrailingStopsTrainingData3
from currency_conversion.trailing_stops3 import TrailingStopsData3
from currency_conversion.trailing_stops3_real_time_data import TrailingStopsData3RealTimeData
from currency_conversion.trailing_stops_project_data import TrailingStopsProjectData
from currency_conversion.trailing_stops_project import TrailingStopsDataProject
from currency_conversion.trailing_stops_project_real_time_data import TrailingStopsDataProjectRealTimeData
from currency_conversion.trailing_stops_project_stored_data import TrailingStopsDataProjectStoredData
